version: '3.1'
services:
  mongo:
    image: mongo:4.0.7-xenial
    restart: always
    ports:
      - '27017:27017'
  mongo-express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongo
    ports:
      - '8888:8081'
